# Generated by Django 5.1.3 on 2025-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking_website", "0002_alter_account_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
