# Generated by Django 5.1.3 on 2025-01-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking_website", "0004_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
